### ISSUE TITLE
Error When importing test domain

### ISSUE THREAD

**Issue by bobuehlein** [nicksantamaria/rackspace_to_route53#1]
Hey there.

Thanks for your hard work on this script. I am getting an error when I try to move over one domain (as a test). The error is

rs_to_53.rb:27:in `get_records': undefined method`records' for nil:NilClass (NoMethodError)
    from rs_to_53.rb:75:in `migrate'
    from rs_to_53.rb:90:in`block in <main>'
    from rs_to_53.rb:89:in `each'
    from rs_to_53.rb:89:in`<main>'

I renamed the file on my box to rs_to_53.rb 

The zone has multiple txt, srv, and cname records.  One MX record and one A record.  Is it the txt/srv records causing issues?

Thanks again.

**Comment by bobuehlein** [comment]
OK. Looks like it likes one of my domains, minus the srv record and only one cname.  But No SRV records are being moved over.

Thanks once again.
